#!/bin/sh

# script/update: Update application to run for its current checkout.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

echo "==> Removing current saltstack"
sudo rm -Rf /srv/salt
sudo rm -Rf /srv/pillar
echo "==> Copying saltstack"
sudo cp -Rf saltstack/salt /srv/salt
sudo cp -Rf saltstack/pillar /srv/pillar
echo "==> Setting access permissions to saltstack"
sudo chmod -R 0644 /srv/salt
sudo chmod -R 0644 /srv/pillar

echo "==> Running salt-call..."
sudo salt-call state.highstate
